export const MONDAY_START = 'MONDAY_START';
export const MONDAY_SUCCESS = 'MONDAY_SUCCESS';
export const MONDAY_INPUT = 'MONDAY_INPUT';
export const MONDAY_FAILED = 'MONDAY_FAILED';

export const TUESDAY_START = 'TUESDAY_START';
export const TUESDAY_SUCCESS = 'TUESDAY_SUCCESS';
export const TUESDAY_INPUT = 'TUESDAY_INPUT';
export const TUESDAY_FAILED = 'TUESDAY_FAILED';

export const WEDNESDAY_START = 'WEDNESDAY_START';
export const WEDNESDAY_SUCCESS = 'WEDNESDAY_SUCCESS';
export const WEDNESDAY_INPUT = 'WEDNESDAY_INPUT';
export const WEDNESDAY_FAILED = 'WEDNESDAY_FAILED';

export const THURSDAY_START = 'THURSDAY_START';
export const THURSDAY_SUCCESS = 'THURSDAY_SUCCESS';
export const THURSDAY_INPUT = 'THURSDAY_INPUT';
export const THURSDAY_FAILED = 'THURSDAY_FAILED';

export const FRIDAY_START = 'FRIDAY_START';
export const FRIDAY_SUCCESS = 'FRIDAY_SUCCESS';
export const FRIDAY_INPUT = 'FRIDAY_INPUT';
export const FRIDAY_FAILED = 'FRIDAY_FAILED';

export const SATURDAY_START = 'SATURDAY_START';
export const SATURDAY_SUCCESS = 'SATURDAY_SUCCESS';
export const SATURDAY_INPUT = 'SATURDAY_INPUT';
export const SATURDAY_FAILED = 'SATURDAY_FAILED';

export const SUNDAY_START = 'SUNDAY_START';
export const SUNDAY_SUCCESS = 'SUNDAY_SUCCESS';
export const SUNDAY_INPUT = 'SUNDAY_INPUT';
export const SUNDAY_FAILED = 'SUNDAY_FAILED';
